---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: eventstreams
  name: eventstreams-kafka-broker
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - create
      - watch
      - update
      - delete
      - list
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - create
      - watch
      - update
      - delete
      - list